## gfb.codes ---------------------------2025-05-01
##  Groundfish database codes -- GFBioSQL
## ------------------------------------------NO|RH
gfb.codes <- list(
	AC = c('field'="ACTIVITY_CODE", '1'="Trawl biomass survey", '2'="Larval survey", '3'="Hydroacoustic survey", '4'="Biological sampling survey",
		'5'="Submersible survey", '6'="Nearshore rockfish survey", '7'="Oceanographic survey", '8'="Seamount survey", '9'="Trap biomass survey",
		'10'="Dive survey", '11'="Tagging", '12'="HS multispecies assemblage BT survey", '13'="GIG POP BT survey", '14'="WCVI thornyhead BT survey",
		'15'="SOG hake survey", '16'="WCVI hake survey", '17'="HS Pcod monitoring BT survey", '18'="YYR charter LL survey", '19'="SBF research & assessment trap survey",
		'20'="Jig survey", '21'="QCS synoptic BT survey", '22'="WCVI synoptic BT survey", '24'="IPHC LL survey", '25'="Multispecies small-mesh (shrimp) BT survey",
		'26'="HS synoptic BT survey", '27'="WCHG synoptic BT survey", '29'="HS juvenile FF survey", '30'="Hake stock delineation", '31'="Joint CA/US hake acoustic survey",
		'32'="SOG ecosystem research initiative acoustic survey", '33'="SOG synoptic BT survey", '34'="Hagfish experimental fishery",
		'35'="Combined submersible and fishing survey", '36'="YYR troll survey", '37'="NMFS triennial BT survey - Vancouver region",
		'38'="SOG lingcod YOY BT survey", '39'="SOG dogfish LL survey", '40'="Historical dogfish tagging survey", '41'="Historical SOG hake and pollock study",
		'42'="Historical herring survey", '43'="La Perouse survey", '44'="Shellfish deep-water BT survey", '45'="WWR acoustic survey", '46'="Big Skate tagging survey",
		'47'="Eulachon migration study BT survey", '48'="HBLL survey - inside North", '49'="HBLL survey - inside South", '50'="HBLL survey - outside North",
		'51'="HBLL survey - outside South"),
	ameth = c('field'="AGEING_METHOD_CODE", '0'="Unknown", '1'="Otolith surface only", '2'="Otolith thin sectioned", '3'="Otolith broken and burnt",
		'4'="Otolith burnt and thin sectioned", '5'="Otolith (unknown)", '6'="Dorsal fin cross-section", '7'="Pectoral fin",
		'8'="Pelvic fin", '9'="Unknown fin", '10'="Scale", '11'="Dorsal spine", '12'="Vertebrae", '13'="Length",
		'14'="Pre-opercular", '15'="Anal fin", '16'="Surface and broken/burnt", '17'="Otolith broken and baked"),
	ART = c('field'="AGE_READING_TYPE_CODE", '0'="Unknown", '1'="Final", '2'="Primary", '3'="Precision test", '4'="Secondary"),
	CAC = c('field'="COLLECTED_ATTRIBUTE_CODE", '0'="Unknown", '1'="Gonads", '2'="Parasites", '3'="Stomachs", '4'="Genetic tissues", '5'="Gillrakers",
		'6'="Genetic tissues - pooled for sample", '7'="Teeth", '8'="Liver", '9'="Caudal thorns", '20'="Otoliths",
		'21'="Scales", '22'="Dorsal fin", '23'="Pectoral fin", '24'="Dorsal spine", '25'="Vertebra",
		'26'="Pre-opercular", '27'="Anal fin ray", '28'="Pelvic fin ray", '29'="Hypural bone", '30'="Skate egg case",
		'31'="Tissue for mercury analysis", '32'="Head", '33'="Coded wire tag", '34'="Recovered tag", '35'="Whole specimen",
		'36'="Muscle tissue for isotope analysis", '37'="Photos (sequence numbers)", '38'="Blood", '39'="User-defined collected attribute #1 for field use",
		'40'="User-defined collected attribute #2 for field use", '41'="Eyeballs", '42'="Muscle tissue for reference genomes", '43'="Slide - dorsal fin",
		'44'="Slide - pectoral fin", '45'="Slide - dorsal spine", '46'="Slide - anal fin ray", '47'="Slide - pelvic fin ray", '48'="Otolith photo"),
	cver = c('field'="CATCH_VERIFICATION_CODE", '0'="Unknown", '1'="Sorted and weighed", '2'="Subsampled and weighed", 
		'3'="Visual estimate of weight", '4'="count * unknown mean wt", '5'="Count * mean wt from sample", 
		'6'="Weight calculated from length-weight relationship", '7'="Trace amount -- visual estimate", 
		'8'="Calculated -- total catch wt minus bycatch wt", '9'="Count only", '10'="Sorted & weighed by factory crew", 
		'11'="Subsample measured & converted", '12'="Catch not weighed or counted", '13'="Count and visual estimate of weight", 
		'14'="Tubs counted with avg wt", '15'="Visual estimate of count", '16'="Volume measurement", 
		'17'="Weight on portion of belt x number of belts observed (Nemesis, 2007)", '18'="Weighed but not sorted", 
		'19'="Count, does not include drop-offs", '20'="Catch information stored in fos database", '21'="Trace weight, with count", 
		'22'="Combination of extrapolated subsample + sorted", '23'="Head-only weight (longline surveys)", 
		'24'="Head-only count (longline surveys)", '25'="Total sort & weigh with calculated count", '26'="Tubs counted with avg wt & calculated count",
		'27'="Tubs counted with avg wt for part of catch, proportion applied to total catch", '28'="Visual estimate of weight & calculated count",
		'29'="Lost at surface (count only)", '30'="Subsampled and weighed -- will be automatically added to unsorted"),
	exist = c('field'="EXISTENCE_ATTRIBUTE_CODE", '1'="Sarcotaces parasites", '2'="XXXX parasites", '3'="YYYY parasites", '4'="Bright colour morph YYR",
		'5'="Dark colour morph YYR", '6'="Scars/net marks - AMR salmon", '7'="Vented - rockfish", '8'="Unvented - rockfish", '9'="Clipped adipose - salmon",
		'10'="Right-eyed flatfish", '11'="Left-eyed flatfish", '12'="Lingcod (YOY)", '13'="Lingcod - 1+", '14'="Lingcod - adult", '15'="Tumour", 
		'16'="REBS - Rougheye (user guess)", '17'="REBS - Blackspotted (user guess)", '18'="SMA6 & MTSNP COI_496 RESOLVED GENETIC ID: BLACKSPOTTED ROCKFISH",
		'19'="SMA6 & MtSNP COI_496 resolved: Rougheye Rockfish", '20'="SMA6 & MtSNP COI_496 resolved: hybrid (REBS) F1+", 
		'21'="SMA6 & MtSNP COI_496 resolved: hybrid (REBS) F2+", '22'="SMA6 & MtSNP COI_496 resolved: failure", 
		'23'="SMA6: Blackspotted/Blackspotted - nuclear DNA marker USMA6 alleles are BSR", '24'="SMA6: Rougheye/Rougheye - nuclear DNA marker USMA6 alleles are RER",
		'25'="SMA6: Blackspotted/Rougheye - nuclear DNA marker USMA6 are BSR and RER", '26'="SMA6: no amplification of locus (failure)",
		'27'="MTSNP: Blackspotted - mitochondrial DNA single nucleotide polymorphism COI_496_C: BSR", 
		'28'="MTSNP: Rougheye - mitochondrial DNA single nucleotide polymorphism COI_496_T: RER", 
		'29'="MTSNP: no amplification of locus (failure)", '30'="Parabranchial cysts", '31'="REBS - hybrid (user guess)", 
		'32'="Eulachon parasitic worm on ovaries", '33'="Eulachon teeth on top of mouth", '34'="Eulachon teeth on bottom of mouth", '35'="Eulachon teeth on tongue",
		'36'="User-defined existence attribute #1 for field use", '37'="User-defined existence attribute #2 for field use", '38'="Eulachon teeth absent"),
	fid = c('field'="FID_CODE", '1'="Trawl (bottom + midwater)", '2'="Halibut (+Sablefish) longline", '3'="Sablefish (+Halibut) trap", 
		'4'="Dogfish/Lingcod (Shed II troll)", '5'="H&L Rockfish (ZN, Inside, Outside)", '8'="Groundfish longline", '9'="Foreign"), 
	gear = c('field'="GEAR_CODE", '0'="Unknown", '1'="Bottom trawl", '2'="Trap", '3'="Gillnet", '4'="Handline", '5'="Longline", '6'="Midwater trawl",
		'7'="troll", '8'="Unknown trawl", '9'="Seine", '10'="Jig", '11'="Shrimp trawl", '12'="Recreational", '13'="Prawn trap", 
		'14'="Tucker trawl", '15'="Plankton sampler", '16'="Twin beam trawl", '17'="Hand seine", '18'="Purse seine", 
		'19'="Bongo net", '20'="Profiling CTD", '21'="Camera", '22'="DAISY"),
	major =c('field'="MAJOR_STAT_AREA_CODE", '0'="Unknown: no position information", '1'="4B: Strait of Georgia", '2'="3B: Cape Flattery", 
		'3'="3C: SW Vancouver Island", '4'="3D: NW Vancouver Island", '5'="5A: Southern Queen Charlotte Sound", '6'="5B: Northern Queen Charlotte Sound",
		'7'="5C: Southern Hecate Strait", '8'="5D: Northern Hecate Strait", '9'="5E: West Coast Haida Gwaii", '10'="Alaska", 
		'11'="British Columbia offshore waters", '22'="Oregon -- used for Sablefish recoveries", '23'="California - used for Sablefish recoveries",
		'24'="Mexico - used for Sablefish recoveries", '40'="Russia", '50'="Japan", '61'="1A: US-Mexico border to Piedras", 
		'62'="1B: Piedras Blancas to Cape Mendocino", '63'="1C: Cape Mendocino to OR-CA border", '64'="2A: OR-CA border to Cape Blanco",
		'65'="2B: Cape Blanco to Cape Perpetua", '66'="2C: Cape Perpetua to Cape Falcon", '67'="3A: Cape Falcon to Cape Elizabeth", 
		'68'="4A: Puget Sound", '71'="3CD: West Coast Vancouver Island", '72'="3D5A: NW Vancouver Island and Southern QC Sound",
		'73'="5AB: Queen Charlotte Sound", '74'="5BC: Northern QC Sound and Southern Hecate Strait", '75'="5CD: Hecate Strait",
		'76'="5DE: Northern Hecate Strait and West Coast Haida Gwaii", '77'="5BE: Northern QC Sound and West Coast Haida Gwaii",
		'99'="Undefined: position info. but does not fall into known area"), 
	morpho = c('field'="MORPHOMETRICS_ATTRIBUTE_CODE", '0'="Unknown", '1'="Fork length", '2'="Standard length", '3'="Origin of dorsal fin to insertion of anal fin len",
		'4'="Total length", '5'="Head length", '6'="Dorsal fin - fork length", '7'="Hypural length", '8'="Estimated fork length", '10'="Whole round weight",
		'11'="gutted weight", '12'="Head-off weight", '13'="J-cut dhoff weight", '14'="Total gonad weight", '15'="Somatic weight", '16'="glazed J-cut dhoff wt",
		'17'="Liver weight", '18'="Snout to post. edge 2nd dorsal fin - Ratfish & Skates", '19'="Bell diameter-jellyfish", '20'="Mantle length-squid",
		'21'="Skate wingspan", '22'="Girth", '23'="Frozen J-cut dhoff weight (not glazed)", '24'="Anterior of 1st dorsal to hypural",
		'25'="Snout to post. edge 1st dors fin", '26'="Fork length - fish gilled, gutted, gonads intact", '27'="Calc fork len(cm) = [(head len(mm)+19.3)/2.97]",
		'28'="Fork length - fish frozen and thawed", '29'="Whole round weight - fish frozen and thawed", '30'="Snout to anterior edge 1st dorsal fin",
		'31'="Snout to anterior edge of anal fin length", '32'="Weight - fish gilled, gutted, gonads intact", '33'="Pre-caudal length", '34'="Total gonad volume",
		'35'="Calc fork len = [(dorsal fin-fork len)*1.258]-1.8", '36'="Dressed head off weight", '37'="Interdorsal length",
		'38'="Insertion of pectoral fin to fork of tail", '39'="Dressed head on weight", '40'="Body weight with stomach contents removed", '41'="Carapace length"),
	narc = c('field'="NOT_AVAILABLE_REASON_CODE", '1'="Specimen damaged", '2'="Possible error in recording", '3'="Forgot", '4'="Scientist interfered", '5'="Outlier", 
		'6'="Otoliths destroyed", '7'="Otoliths recorded by agelab -- location unknown", '8'="Otoliths not recorded by agelab -- location unknown", 
		'9'="Otoliths collected -- held by another agency", '10'="Tray dumped", '11'="Otoliths collected -- held by tagging program",
		'12'="One otolith missing"),
	RC = c('field'="REASON_CODE", '0'="Unknown", '1'="Species comp. for biomass", '2'="Biological sampling", '3'="Quant. biomass survey", '4'="Genetics study",
		'5'="Assemblage survey", '6'="Standard station", '7'="Tagging", '8'="Multi-purpose", '9'="Acoustic sign verif, spp id/size, target strength",
		'10'="Special permit fishery", '11'="Larval fish survey", '12'="Commercial set", '13'="Sablefish offshore survey", '14'="Sablefish escape ring study",
		'15'="Sablefish standardized inlet survey", '16'="Sablefish deepwater survey", '17'="Live fish for culture", '18'="Predetermined set for HS Pcod surveys", 
		'19'="Skipper selected set for HS Pcod surveys", '20'="Gear calibration", '21'="Exploratory", '22'="Video record for REASON_CODE 9 (acoustics)",
		'23'="Shoreside hake", '24'="Plankton sampling", '25'="Video record for acoustic sign verif, spp size/id", '26'="Hagfish depletion experiment",
		'27'="Hagfish fixed depth stratified survey", '28'="Hagfish Kirby Point index site", '29'="Sablefish standardized offshore survey",
		'30'="Sablefish traditional tagging", '31'="Sablefish offshore systematic tagging", '32'="Sablefish random stratified survey", '33'="CTD vertical cast"),
	scat = c('field'="SPECIES_CATEGORY_CODE", '0'="Unknown", '1'="Unsorted", '2'="Sorted (unknown criterion)", '3'="Keepers", '4'="Discarded", '5'="Remains", 
		'6'="Longline -- fish head only", '8'="Longline/jig -- fish lost at rail/surface"),
	ssid = c('field'="SURVEY_SERIES_ID", '0'="Individual survey", '1'="QCS Synoptic", '2'="HS Assemblage", '3'="HS Synoptic", '4'="WCVI Synoptic",
		'5'="HS Pcod Monitoring", '6'="QCS Shrimp Trawl", '7'="WCVI Shrimp Trawl", '8'="1997 WCHG Rockfish", '9'="1996 WCVI Rockfish", '10'="1995 GIG Rockfish",
		'11'="WCVI Thornyhead", '12'="Combined WCVI/HS/QCS Synoptic", '13'="HBLL Inside", '14'="IPHC Longline", '15'="SOG Lingcod YoY",
		'16'="WCHG Synoptic", '17'="IPHC Longline (3CD)", '18'="IPHC Longline (5AB)", '19'="IPHC Longline (5CD)", '20'="WCVI Synoptic Vancouver Region", 
		'21'="GIG Historical", '22'="HBLL N Outside", '23'="WCVI Thornyhead (no area strata)", '24'="WCVI Thornyhead (2 depth/no area strata)", 
		'25'="WCVI Thornyhead (2 depth/2 area strata)", '26'="GIG Historic GB Reed", '27'="WCVI Synoptic NMFS Triennial Region", 
		'28'="QCS (historic GB Reed + modern QCS synoptic)", '29'="QCS Synoptic (restratified for 2008 POP)", '30'="WCHG Synoptic (without deepest stratum)",
		'31'="WCVI Synoptic (with modified S/N boundaries)", '32'="GIG (restratified 2009 POP)", 
		'33'="1995 GIG (restratified using modern QCS synoptic strata)", '34'="SOG Acoustic", '35'="Sablefish Res + Assess", '36'="HBLL S Outside",
		'37'="WCHG BT 1997 on (180-500m)", '38'="WCVI BT 1996 on (125-500m)", '39'="HBLL North (inside)", '40'="HBLL South (inside)",
		'41'="Inlet SBF Trap", '42'="Offshore SBF Trap", '43'="Offshore SBF Trap II", '44'="QCS BT Footprint", '45'="SOG Synoptic", 
		'46'="Nearshore Shrimp", '47'="PAK Stock Delineation", '48'="Dogfish Surveys", '49'="YYR Longline", '50'="YYR Genetics", 
		'51'="Submersible + LL", '67'="Multispecies Small-mesh BT", '68'="Hake Acoustic", '69'="QCS Synoptic for BIS", '70'="WCVI Synoptic for BIS", 
		'71'="HS Synoptic for BIS", '72'="QCS Synoptic for LNS", '73'="WCVI Synoptic for LNS", '74'="HS Synoptic for LNS", '75'="WCHG Synoptic for LNS", 
		'76'="SOG Dogfish LL", '77'="Commercial Seamount Trips", '78'="Neocaligus EDAS Kit", '79'="NMFS Triennial", 
		'80'="Eulachon Migration (south)", '81'="Integrated Pelagics Ecosystem", '82'="Jig Survey (4B Area 12)", '83'="Jig Survey (4B Area 13)",
		'84'="Jig Survey (4B Area 15)", '85'="Jig Survey (4B Area 16)", '86'="Jig Survey (4B Area 18)", '87'="Jig Survey (4B Area 19)", 
		'88'="Eulachon Migration (north)", '89'="Nearshore Prawn Trap", '90'="Intl Year Salmon Midwater Trawl and Oceanographic Survey", 
		'91'="Basin and Coastal Salmon Interactions (BCSI)", '92'="SOG Dogfish LL (J-hook)", '93'="SOG Dogfish LL (circle hook)", 
		'94'="Historic GB Reed WCVI (1969-1972)", '95'="SOG Midwater Salmon",
		'350'="Sablefish Trap", '670'="Shrimp Trawl", '820'="Jig Surveys", '999'="Commercial Fishery"),
	ssrc = c('field'="SAMPLE_SOURCE_CODE", '0'="Unknown", '1'="Unsorted", '2'="Keepers", '3'="Discards", '4'="Stomach contents", '5'="13/0 circle squid", 
		'6'="14/0 circle herring", '7'="J herring", '8'="E1 escape ring treatment (for GFBioField)", 
		'9'="E2 escape ring treatment (for GFBioField)", '10'="E3 escape ring treatment (for GFBioField)", 
		'11'="E4 escape ring treatment (for GFBioField)", '12'="Escape ring TRAP_MODIFICATIONS_CODE 21", 
		'13'="Escape ring TRAP_MODIFICATIONS_CODE 22", '14'="Escape ring TRAP_MODIFICATIONS_CODE 23", 
		'15'="Escape ring TRAP_MODIFICATIONS_CODE 24", '16'="EM length measurement of discards"),
	stype = c('field'="SAMPLE_TYPE_CODE", '0'="Unknown", '1'="Total catch", '2'="Random", '4'="Selected", '5'="Stratified", 
		'6'="Random from randomly assigned set", '7'="Random from set after randomly assigned set", 
		'8'="Random from set requested by vessel master", '9'="Selected juveniles", '10'="Selected adults", 
		'11'="Other -- see sample_type_comment", '12'="Selected first N specimens", '13'="Selected first N specimens -- whole fish only",
		'14'="Selected tag recoveries", '15'="Selected males", '16'="Selected females", '17'="Unknown sample type for NMFS triennial survey"),
	success = c('field'="SUCCESS_CODE", '0'="Undefined", '11710'="Unknown", '11711'="Fully usable", '11712'="Malfunction / damage",
		'11713'="Lost", '11714'="Water haul"), 
	ttype = c('field'="TRIP_SUB_TYPE_CODE", '1'="Non-obs domestic", '2'="Research", '3'="Charter", '4'="Obs domestic", '5'="Observed JV", 
		'6'="Non-obs JV", '7'="Polish comm natl", '8'="Russian comm natl", '9'="Russian comm supp", '10'="Polish comm supp",
		'11'="Recreational", '12'="Japanese obs natl", '13'="Japanese comm", '14'="Unknown foreign"),
	use =c('field'="USABILITY_CODE", '0'="Unknown", '1'="Fully usable", '2'="Fail, but all data usable", '3'="Fail, catch only usable", 
		'4'="Fail, spec. comp. usable", '5'="Fail, no usable data", '6'="Gear torn, all data ok", '7'="Gear torn, catch amts ok", 
		'8'="Gear torn, spec. comp. ok", '9'="Gear torn, no data usable", '10'="Gear lost or destroyed", '11'="Unusable -- out of depth range",
		'12'="Not all traps fishing correctly", '13'="Unusable for cpue estimation", '16'="Unusable -- not enough bottom contact time",
		'17'="Out of depth range but all other data usable", '19'="Some/all skates lost -- data unusable for cpue est", 
		'20'="Snarls in longline -- data unusable for cpue est", '21'="Usable but omit from swept area calculations", 
		'22'="Usable but removed due to re-definition of survey area", '23'="Test tow -- no usable data", 
		'24'="Midwater trawl touched bottom -- data usable", '25'="Bottom trawl fished in midwater -- data usable", 
		'26'="Fail, multi-net plankton sampler not preforming properly (flowmeter problems, weight adjustments)", 
		'27'="Usable but omit from any biomass calculations", '28'="Unusable -- gear deployed in an area closed to fishing", 
		'29'="Unusable trap -- dislodged bait", '30'="Unusable trap -- octopus (Rubescens/small red) in trap", 
		'31'="Unusable trap -- octopus (Dofleini/giant red) in trap", '32'="Unusable trap -- octopus (small red and giant red) in trap", 
		'33'="Unusable trap -- octopus (unknown species) in trap", '34'="Unusable trap -- carapace shucks in trap (evidence of octopus)",
		'35'="Unusable hagfish barrel trap -- broken or damaged (tunnel, cone, etc.), lid off",
		'36'="Unbaited hagfish barrel trap -- unusable for CPUE estimation", '37'="Hagfish barrel trap -- broken or damaged but recorded as useable",
		'38'="Trap: escape ring open", '39'="Trap: tunnel line broken", '40'="Trap: trap open", '41'="Trap: gilled in trap", 
		'42'="Trap: escape panel open", '43'="Trap: gilled in tunnel", '44'="Trap: snarl", '45'="Trap: bait problem", '46'="Problem with trap",
		'47'="Trap: other problem", '48'="Trap: gilled in escape ring", '49'="Trap: tunnel loose or not correctly tied", 
		'50'="Trap: unusable for CPUE estimation", '51'="Unusable hook and line -- fishing gear set across longline survey set", 
		'52'="Usable but omit from any geospatial analysis", '53'="Data lost -- data unusable for CPUE est")
)
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~gfb.codes


